CREATE TABLE `customers` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `business_name` varchar(200) NOT NULL,
    `balance` decimal(8,2) DEFAULT NULL,
    `balance_updated` timestamp NULL DEFAULT NULL,
    `config_id` int(11) DEFAULT '0',
    `signup_link_from` enum('MS','WEB','MS-NEW','WEB-NEW') DEFAULT NULL COMMENT 'from where the signup link is been generated',
    `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `clients_fname` varchar(150) NOT NULL,
    `clients_sname` varchar(10) NOT NULL,
    `customer_id` varchar(200) NOT NULL,
    `business_number` varchar(20) NOT NULL,
    `business_street` varchar(200) NOT NULL,
    `business_city` varchar(200) NOT NULL,
    `business_county` varchar(200) NOT NULL,
    `business_post_code` varchar(50) NOT NULL,
    `business_phone_number` varchar(12) NOT NULL,
    `business_email` varchar(150) NOT NULL,
    `customers_number` varchar(20) NOT NULL,
    `customers_street` varchar(150) NOT NULL,
    `customers_city` varchar(150) NOT NULL,
    `customers_county` varchar(200) NOT NULL,
    `customers_post_code` varchar(50) NOT NULL,
    `customers_mobile` varchar(12) NOT NULL,
    `customers_email` varchar(150) NOT NULL,
    `customer_password` text NOT NULL,
    `customer_level` int(2) NOT NULL DEFAULT '10',
    `contract_rent` varchar(6) NOT NULL,
    `contract_length` varchar(25) NOT NULL DEFAULT '12',
    `notice_period` varchar(25) NOT NULL DEFAULT '30',
    `setup_charged` enum('TRUE','FALSE') DEFAULT NULL,
    `setup_fee` float(10,2) DEFAULT NULL,
    `extra_comments` text NOT NULL,
    `services_description` varchar(100) NOT NULL DEFAULT 'Data and Merchant Management Services',
    `status` int(1) NOT NULL,
    `progress_status` int(11) NOT NULL,
    `progress_date` datetime DEFAULT NULL,
    `agree` text NOT NULL,
    `ip_address` text NOT NULL,
    `VPSTxId` text NOT NULL,
    `SecurityKey` text NOT NULL,
    `TxAuthNo` text NOT NULL,
    `bank_verification_status` enum('VERIFIED','VERIFY LATER','NOT VERIFIED') NOT NULL DEFAULT 'VERIFY LATER',
    `account_verification_status` enum('VERIFIED','NOT-VERIFIED') DEFAULT 'NOT-VERIFIED',
    `internal_transfer_fee_percent` decimal(5,2) DEFAULT '3.40',
    `internal_transfer_fee_fixed` decimal(5,2) DEFAULT '0.20',
    `internal_transfer_status` enum('ENABLED','DISABLED') DEFAULT 'DISABLED',
    `is_supplier` enum('TRUE','FALSE') DEFAULT 'FALSE',
    `application_complete` tinyint(4) NOT NULL,
    `signature_token` varchar(255) NOT NULL,
    `enabled_withdrawal_once` enum('ENABLED','DISABLED') DEFAULT 'DISABLED' COMMENT 'This flag is used for enabling money withdrawal for this client. Customers are advised to verify their accounts before withdrawing any money from their account. If they want to byepass this verification, admin users can enable this flag that will allow clients to withdraw money once.',
    PRIMARY KEY (`id`),
    KEY `progress_status_setup_charged` (`progress_status`,`setup_charged`) USING BTREE
  ) ENGINE=InnoDB AUTO_INCREMENT=63190537 DEFAULT CHARSET=latin1;